"use strict";
// type inference in type typescript refer to the ability of the typeScript compiler automaticalyy detemine and assign type to variables, expression and function return values based on their usage and context in the code....
